FIND_PATH(EDITLINE_INCLUDE_DIR editline/readline.h)
FIND_LIBRARY(EDITLINE_LIBRARY NAMES edit)


IF (EDITLINE_INCLUDE_DIR AND EDITLINE_LIBRARY)
  SET(EDITLINE_FOUND TRUE)
ENDIF ()


IF (EDITLINE_FOUND)
  IF (NOT Editline_FIND_QUIETLY)
    MESSAGE(STATUS "Found editline: ${EDITLINE_LIBRARY}")
  ENDIF (NOT Editline_FIND_QUIETLY)
ELSE ()
  IF (Editline_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find editline")
  ENDIF ()
ENDIF ()