FIND_PATH(READLINE_INCLUDE_DIR readline/readline.h)
FIND_LIBRARY(READLINE_LIBRARY NAMES readline)


IF (READLINE_INCLUDE_DIR AND READLINE_LIBRARY)
  SET(READLINE_FOUND TRUE)
ENDIF ()


IF (READLINE_FOUND)
  IF (NOT Readline_FIND_QUIETLY)
    MESSAGE(STATUS "Found GNU readline: ${READLINE_LIBRARY}")
  ENDIF ()
ELSE ()
  IF (Readline_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find GNU readline")
  ENDIF ()
ENDIF ()